# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: ChaosAgent
  demands:
  - visualstudio

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: VSBuild@1
  displayName: 'Build ChaosLab'
  inputs:
    solution: 'ChaosLab.sln'
    platform: 'x64'
    configuration: 'Release'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: 'ChaosMathTest.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)\build\x64\Release'
  
coverage:
  status:           #Code coverage status will be posted to pull requests based on targets defined below.
    comments: on    #Off by default. When on, details about coverage for each file changed will be posted as a pull request comment. 
    diff:           #diff coverage is code coverage only for the lines changed in a pull request.
      target: 50%   #set this to a desired %. Default is 70%