# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: ChaosAgent
  demands:
  - visualstudio

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: VSBuild@1
  displayName: 'Build ChaosCV'
  inputs:
    solution: 'Inception\ChaosCV\ChaosCV.vcxproj'
    platform: 'x64'
    configuration: 'Release'

- task: VSBuild@1
  displayName: 'Build ChaosMath Test'
  inputs:
   solution: 'Tests\ChaosMathTest\ChaosMathTest.vcxproj'
   platform: 'x64'
   configuration: 'Release'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: 'ChaosMathTest.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)\build\Release'