# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'
  #name: ChaosAgent
  #demands:
  #- visualstudio

steps:
- task: VSBuild@1
  displayName: 'Build ChaosLab'
  inputs:
    solution: 'ChaosLab.sln'
    platform: 'x64'
    configuration: 'Release'
 
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: 'ChaosMathTest.dll'
    codeCoverageEnabled: true
    searchFolder: '$(System.DefaultWorkingDirectory)\build\x64\Release'
    platform: 'x64'
    configuration: 'Release'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '$(Agent.TempDirectory)\TestResults\*.trx'




