# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'
  #name: ChaosAgent
  #demands:
  #- visualstudio

steps:
- task: VSBuild@1
  displayName: 'Build ChaosLab'
  inputs:
    solution: 'ChaosLab.sln'
    platform: 'x64'
    configuration: 'Release'
 
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: 'ChaosMathTest.dll'
    codeCoverageEnabled: true
    searchFolder: '$(System.DefaultWorkingDirectory)\build\x64\Release'
    platform: 'x64'
    configuration: 'Release'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '$(Agent.TempDirectory)\TestResults\*.trx'
  
- task: PowerShell@2
  displayName: 'Coverlet'
  inputs:
    targetType: 'inline'
    script: |
      "Install tools"
      &dotnet tool install dotnet-reportgenerator-globaltool --tool-path . --version 4.0.12
      &dotnet tool install coverlet.console --tool-path . --version 1.4.1

      "nmake rports dir"
      mkdir .\reports
      
      "run tests:"
      $coverlet = "$pwd\coverlet.ext" 
      $vstest = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe"
      &$coverlet $(System.DefaultWorkingDirectory)\build\x64\Release\ChaosMathTest.dll --target "$vstest" --targetarg "ChaosMathTest.dll --logger:trx --enablecodecoverage" --format "cobertura"





